//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitymagaza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magaza
    {
        public int MagazaNo { get; set; }
        public string MagazaAdi { get; set; }
        public Nullable<decimal> MagazaCiro { get; set; }
        public string MagazaAdres { get; set; }
        public Nullable<System.DateTime> SevkiyatTarihi { get; set; }
        public string SevkiyatGunu { get; set; }
    }
}
