//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace entitymagaza
{
    using System;
    using System.Collections.Generic;
    
    public partial class Malzemeler
    {
        public int MalzemeNo { get; set; }
        public Nullable<int> MagazaNo { get; set; }
        public string MalzemeAdi { get; set; }
        public Nullable<int> MalzemeAdet { get; set; }
        public Nullable<decimal> MalzemeBirimFiyat { get; set; }
        public Nullable<int> MalzemeKod { get; set; }
        public string MalzemeAciklama { get; set; }
    }
}
